name: Tests # Force workflow refresh

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  workflow_dispatch: # Enable manual triggering

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Debug matrix values
      run: |
        echo "Operating System: ${{ matrix.os }}"
        echo "Python Version: ${{ matrix.python-version }}"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "${{ matrix.python-version }}"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
    
    - name: Test Convo examples
      run: |
        python -m convo examples/hello_world.convo
        python -m convo examples/variables.convo
        python -m convo examples/functions.convo
        python -m convo examples/control_flow.convo
    
    - name: Test main entry point
      run: |
        python main.py examples/hello_world.convo
